name: End-to-end test
on: push 
jobs: 
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/Checkout@v3
      - name: Cypress run
        uses: cypress-io/github-action@v5
      - uses: actions/upload-artifact@v3
        if: failure()
        with: 
          name: cypress-screenshots
          path: cypress-sreenshots
      - uses: actions/upload-artifact@v3
          if: always()
        name: cypress-videos
        path: cypress-videos
